@username = "email@email.com"
@password = "pass123"

@username_ = "email@email.com"

POST http://localhost:5000/usuario HTTP/1.1
Content-Type: application/json

{
    "nome": "Mateus Vitor",
    "email": "email@email.com",
    "password": "pass123"
}

POST http://localhost:5000/auth HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=utf-8
Authorization: Basic {{username}} {{password}}


POST http://localhost:5000/modalidade HTTP/1.1
Content-Type: application/json

{
    "nome": "Basketball",
    "icone": "basketball"
}

POST http://localhost:5000/modalidade HTTP/1.1
Content-Type: application/json

{
    "nome": "Futsal",
    "icone": "futsal"
}

GET http://localhost:5000/modalidades HTTP/1.1
Content-Type: application/json

POST http://localhost:5000/atletica HTTP/1.1
Content-Type: application/json

{
    "nome": "Regente",
    "curso": "Bacharel Interdisciplinar em Ciência e Tecnologia",
    "icon": "icon.png",
    "email": "email@email.com",
    "instagram": "@insta",
    "facebook": "facebook",
    "twitter": "@twitter"
}

POST http://localhost:5000/atletica HTTP/1.1
Content-Type: application/json

{
    "nome": "Muralha",
    "curso": "Engenharia Civil",
    "icon": "icon.png",
    "email": "email_@email.com",
    "instagram": "@insta_",
    "facebook": "facebook_",
    "twitter": "@twitter_"
}

GET http://localhost:5000/atletica/0 HTTP/1.1
Content-Type: application/json

GET http://localhost:5000/atleticas HTTP/1.1
Content-Type: application/json

POST http://localhost:5000/jogo HTTP/1.1
Content-Type: application/json 

{
    "modalidade": "Basket",
    "time1": 0,
    "time2": 1,
    "local": "UFMA",
    "data": "2021-09-08 00:00"
}

GET http://localhost:5000/jogo/0 HTTP/1.1
Content-Type: application/json

GET http://localhost:5000/jogos HTTP/1.1
Content-Type: application/json